# Netlify Configuration for Air Tour React App

[build]
  # Build command
  command = "npm run build"
  
  # Directory with production build
  publish = "dist"
  
  # Node version
  node_version = "18"

# Redirects for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Environment variables (set these in Netlify dashboard)
# VITE_STRIPE_PUBLISHABLE_KEY=pk_test_your_key_here
# VITE_API_URL=https://your-backend-api.com

# Build plugins (optional)
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"

# Dev server settings
[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  autoLaunch = false

